image: docker:latest

stages:
    - "build prod"
    - "deploy prod"

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DEMO_DIR_HOST: /var/bezones/nextsource/demo/
    PROD_DIR_HOST: /var/bezones/nextsource/prod/
    DEV_SERVER_SSH: bezones@git.bezones.cz
    PROD_SERVER_SSH: bezones@git.bezones.cz
before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_CONFIG" > ~/.ssh/config
    - echo "$SSH_DEPLOY_KEY" > ~/.ssh/deploy
    - chmod -R 600 ~/.ssh
    - docker info
    - docker login registry.bezones.cz -u $DOCKER_LOGIN_NAME -p $DOCKER_LOGIN_PASSWORD

services:
    - docker:dind

build from prod:
    stage: "build prod"
    only:
        refs:
            - master
    script:
        - docker build -f ./docker/Dockerfile --no-cache -t ${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH} .
        - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH} registry.bezones.cz/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}
        - docker push registry.bezones.cz/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}

deploy to host prod:
    stage: "deploy prod"
    only:
        refs:
            - master
    script:
        - ssh $PROD_SERVER_SSH -p 2222 "mkdir -p $PROD_DIR_HOST"
        - scp -P 2222 -rp ./deploy/prod/* $PROD_SERVER_SSH:$PROD_DIR_HOST/
        - ssh $PROD_SERVER_SSH -p 2222 "sudo docker login registry.bezones.cz -u $DOCKER_LOGIN_NAME -p $DOCKER_LOGIN_PASSWORD"
        - ssh $PROD_SERVER_SSH -p 2222 "cd $PROD_DIR_HOST && sudo docker-compose pull"
        - ssh $PROD_SERVER_SSH -p 2222 "cd $PROD_DIR_HOST && sudo docker-compose down"
        - ssh $PROD_SERVER_SSH -p 2222 "cd $PROD_DIR_HOST && sudo docker-compose up -d"
